nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        allow_credentials: true
        max_age: 3600
#    paths:
#        '^/api/':
#            allow_origin: ['*']
#            allow_headers: ['X-Custom-Auth', 'Origin', 'X-Requested-With', 'Content-Type', 'Accept']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
#        '^/':
#            origin_regex: true
#            allow_origin: ['*']
#            allow_headers: ['X-Custom-Auth', 'Origin', 'X-Requested-With', 'Content-Type', 'Accept']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
#            hosts: ['^api\.']